server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server03    # eureka实例的主机名 eureka-server  eureka8761.com
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8762/eureka/
      #defaultZone: http://eureka8762.com:8762/eureka/




